# Generated by Django 5.2.13 on 2026-08-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_student_points_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_classrooms', to='core.teacher'),
        ),
    ]
